# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src

pool: "Azure Pipelines"

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(ContainerRegistry)'
    repository: '$(ContainerRepository)'
    command: 'buildAndPush'
    Dockerfile: 'src/KegMonitor.Web/Dockerfile'
    buildContext: 
    tags: |
      $(Build.BuildId)
      latest