# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/KegMonitor.Broker/KegMonitor.Broker.csproj'
    arguments: '--runtime linux-x64 --no-self-contain --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/broker'
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'src/KegMonitor.Web/KegMonitor.Web.csproj'
    arguments: '--runtime linux-x64 --no-self-contain --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/web'
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/broker'
    ArtifactName: 'broker'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/web'
    ArtifactName: 'web'
    publishLocation: 'Container'


