# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  kegmonitorweb:
    image: kegmonitor
    build:
      context: .
      dockerfile: src/KegMonitor.Web/Dockerfile
    ports:
      - 7101:80
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
