version: "3.6"
services:
  kegmonitor:
    container_name: "kegmonitor"
    build:
      context: .
      dockerfile: src/KegMonitor.Web/Dockerfile
    ports:
      - "${PORT}:80/tcp"
    network_mode: "bridge"
    networks:
      server_net:
        ipv4_address: ${IP_ADDRESS}
    ipc: "private"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "TZ=${TIMEZONE}"
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "ConnectionStrings__DefaultConnection=${CONNECTION_STRING}"
      - "WebDomain=${DOMAIN}"
      - "MigrateDatabaseToLatest=true"
      - "Mqtt__ClientId=${MQTT_CLIENT_ID}"
      - "Mqtt__IpAddress=${MQTT_IPADDRESS}"
      - "Mqtt__Port=${MQTT_PORT}"
      - "Mqtt__Username=${MQTT_USERNAME}"
      - "Mqtt__Password=${MQTT_PASSWORD}"
    volumes:
      - "keg_monitor_app_data:/app/wwwroot/uploads"
    working_dir: "/app"
    restart: "always"
    healthcheck:
      test: "curl --fail http://localhost/health || exit 1"
      interval: 60s
      retries: 2
      start_period: 20s
volumes:
  keg_monitor_app_data:
    external: true
networks:
  server_net:
    external: true