version: "3.6"

services:
  kegmonitor:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    container_name: "kegmonitor"
    build:
      context: .
      dockerfile: src/KegMonitor.Web/Dockerfile
    ports:
      - "${PORT}:80/tcp"
    network_mode: "bridge"
    ipc: "private"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "ConnectionStrings__DefaultConnection=${CONNECTION_STRING}"
      - "WebDomain=${DOMAIN}:${PORT}"
      - "MigrateDatabaseToLatest=true"
      - "Mqtt__ClientId=${MQTT_CLIENT_ID}"
      - "Mqtt__IpAddress=${MQTT_IPADDRESS}"
      - "Mqtt__Port=${MQTT_PORT}"
      - "Mqtt__Username=${MQTT_USERNAME}"
      - "Mqtt__Password=${MQTT_PASSWORD}"
    volumes:
      - "keg_monitor_app_data:/app/wwwroot/uploads"
    working_dir: "/app"
    restart: "always"
    healthcheck:
      test: "curl --fail http://localhost || exit 1"
      interval: 60s
      retries: 5
      start_period: 20s
volumes:
  keg_monitor_app_data:
    external: true