name: Build Docker Image

on:
  pull_request:
    branches: [ "main" ]
    paths: 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    
    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: src/KegMonitor.Web/Dockerfile
        push: false
        tags: pr-${{ github.event.pull_request.number }}
