name: Deploy Docker Image

on:
  push:
    branches: [ "main" ]
    paths: 'src/**'
  pull_request:
    branches: [ "main" ]
    paths: 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ vars.IMAGE_REPOSITORY }}
        tags: |
          ${{ github.run_id }}
          latest
          
    - name: Checkout Source
      uses: actions/checkout@v3
    
    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: src/KegMonitor.Web/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
